version: '3.8'

services:
  jnu-library-ai:
    build: .
    container_name: jnu-library-ai
    ports:
      - "5001:5001"
    environment:
      # 设置API配置 - 根据需要修改
      - API_BACKEND=qwen
      # 如果使用千问API，需要设置API密钥
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
      # 如果使用OpenAI API
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # 如果使用星火API
      - SPARK_APP_ID=${SPARK_APP_ID}
      - SPARK_API_KEY=${SPARK_API_KEY}
      - SPARK_API_SECRET=${SPARK_API_SECRET}
    volumes:
      # 挂载交互统计数据目录（可选）
      - ./interaction_stats:/app/interaction_stats
    restart: unless-stopped
    # 设置共享内存大小（Chrome需要）
    shm_size: 2gb
    # 添加必要的能力
    cap_add:
      - SYS_ADMIN
    # 安全选项
    security_opt:
      - seccomp:unconfined
